name: Проверка стиля кода

on:
  push:
    branches:
      - pr7

jobs:
  run_pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install pylint
          pylint .
